# Neurotorch API Tests

This notebook contains code to test the Neurotorch API

### 0 Imports

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import os
import sys

In [2]:
# SETTINGS

# If the IMPORT_PATH variable is not none, the module will be imported from the given path
IMPORT_PATH: Path|None = Path("../../../neurotorch")

In [3]:
if IMPORT_PATH is not None:
    if not IMPORT_PATH.exists():
        raise FileExistsError()
    sys.path.insert(1, str(IMPORT_PATH))
os.environ["NEUROTORCH_DEBUG"] = "True"
import neurotorchmz
from neurotorchmz import Session
from neurotorchmz.core.session import *
from neurotorchmz.utils.synapse_detection import *

print("Imported neurotorchmz version", neurotorchmz.__version__)

[2025-08-12 15:50:52,843 DEBUG]: Started debugging
[2025-08-12 15:50:52,845 DEBUG]: Found 'apache-maven-3.9.11' in the AppData folder and added 'C:\Users\ABril\AppData\Local\andreasmz\NeurotorchMZ\environment\apache-maven-3.9.11\bin' temporarily to PATH
[2025-08-12 15:50:52,851 DEBUG]: Found 'jdk-24.0.2' in the AppData folder, created JAVA_HOME and added 'C:\Users\ABril\AppData\Local\andreasmz\NeurotorchMZ\environment\jdk-24.0.2\bin' temporarily to PATH
[2025-08-12 15:50:54,637 DEBUG]: Loaded plugin neurotorchmz.plugins.pyimage_j
[2025-08-12 15:50:54,637 DEBUG]: Loaded plugin neurotorchmz.plugins.test_plugin
[2025-08-12 15:50:54,642 ERROR]: Failed to import plugin neurotorchmz.plugins.trace_selector: The plugin is missing the __plugin_name__ string


Imported neurotorchmz version 25.8.1


In [ ]:
session = neurotorchmz.start_background(edition=neurotorchmz.Edition.NEUROTORCH_DEBUG)

[2025-08-12 15:50:57,355 DEBUG]: Testplugin noticed that the session started
[2025-08-12 15:50:57,458 INFO]: Started NeurotorchMZ (GUI) version 25.8.1


[2025-08-12 15:51:13,043 DEBUG]: Opening '+40118_CS1-2_37a+47_iGlu_denoised_only_stimulation_compressed.tiff' with tifffile
[2025-08-12 15:51:13,117 DEBUG]: Calculating mean view for AxisImage '+40118_CS1-2_37a+47_iGlu_denoised_only_stimulation_compressed.tiff-default-img' on axis '(0,)'
[2025-08-12 15:51:13,127 DEBUG]: Calculating std view for AxisImage '+40118_CS1-2_37a+47_iGlu_denoised_only_stimulation_compressed.tiff-default-img' on axis '(0,)'
[2025-08-12 15:51:13,295 DEBUG]: Calculating max view for AxisImage '+40118_CS1-2_37a+47_iGlu_denoised_only_stimulation_compressed.tiff-default-img_diff' on axis '(0,)'
[2025-08-12 15:51:13,299 DEBUG]: Calculating std view for AxisImage '+40118_CS1-2_37a+47_iGlu_denoised_only_stimulation_compressed.tiff-default-img_diff' on axis '(0,)'
[2025-08-12 15:51:13,403 DEBUG]: Calculating max view for AxisImage '+40118_CS1-2_37a+47_iGlu_denoised_only_stimulation_compressed.tiff-default-img_diff' on axis '(1, 2)'
[2025-08-12 15:51:13,406 DEBUG]: Calcu

In [ ]:
# Run everything above this cell

### Session tests

In [ ]:
session2 = Session(edition=neurotorchmz.Edition.NEUROTORCH_DEBUG)

In [ ]:
session2.launch(background=True)

### Detection results tests

In [ ]:
dt = session.roifinder_detection_result

In [ ]:
session.roifinder_detection_result

In [ ]:
dt.append(SingleframeSynapse())

In [ ]:
dt.append(MultiframeSynapse())

In [ ]:
dt[0].rois.append(PolygonalSynapseROI())

In [ ]:
dt[3].rois.append(CircularSynapseROI().set_location(x=10,y=20).set_radius(10).set_frame(0))

In [ ]:
for s in dt:
    print(repr(s))

In [ ]:
dt[0].staged = False

In [ ]:
dt.clear_where(lambda s: not s.staged)

### Convolution filters

In [6]:
imgObj = session.active_image_object

In [ ]:
print(imgObj.img_diff_raw)

In [17]:
print(imgObj.imgDiff)

[[[ 1  0  0 ... -1 -1 -1]
  [ 1  1  0 ... -2 -2 -1]
  [ 0  1  0 ... -1  0  0]
  ...
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0 -1  0]
  [ 0  1  0 ...  0 -1  0]]

 [[-1  0  0 ...  1  1  1]
  [ 0 -1  0 ...  1  1  1]
  [-1 -1  0 ...  0  0  0]
  ...
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  1  0]
  [ 0 -1  0 ...  0  1  0]]

 [[ 1  0  0 ...  0  0  0]
  [ 0  1  0 ...  1  0  0]
  [ 1  1  0 ...  1  0  0]
  ...
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  1  0  0]
  [ 0  1  0 ...  0  0  0]]

 ...

 [[ 0  1  1 ... -1  0 -1]
  [ 1  1  2 ... -1 -1 -1]
  [ 1  1  1 ... -2 -2 -1]
  ...
  [ 5  5  5 ...  1  1  0]
  [ 4  5  5 ...  1  0  1]
  [ 4  3  5 ...  0  0  0]]

 [[ 0 -1  1 ...  0 -1  0]
  [ 0 -1  0 ...  0 -1  0]
  [ 0  0  0 ...  0  0  0]
  ...
  [ 0  1  1 ... -1  0  0]
  [ 1  0  1 ... -1  0  0]
  [ 0  1  0 ...  0  0  0]]

 [[ 0  1  0 ...  0  1  0]
  [ 0  0 -1 ...  1  2  1]
  [-1 -1  0 ...  2  2  1]
  ...
  [ 0  0 -1 ...  0 -1  0]
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]]]


In [ ]:
img = imgObj.imgDiffView(ImageView.SPATIAL).Min

plt.imshow(img)
plt.show()